---
replicaCount: 1

image:
  repository: 073876270065.dkr.ecr.eu-west-1.amazonaws.com/mywebapp
  pullPolicy: IfNotPresent
  tag: latest

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
